# Trigger pipeline on push to the master branch
trigger:
  branches:
    include:
      - master

# Specify the build environment (Linux VM)
pool:
  vmImage: 'ubuntu-latest'

# Steps to be executed
steps:
  # Step 1: Checkout code from the current repository
  - checkout: self
  
  # Step 2: Install Node.js (version 14.x)
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  # Step 3: Install dependencies (using npm)
  - script: npm install
    displayName: 'Install dependencies'

  # Step 4: Run tests
  - script: npm test
    displayName: 'Run tests'

  # Step 5: Build the project
  - script: npm run build
    displayName: 'Build project'

  # Step 6: Publish build artifacts (for later deployment)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dist'
      artifactName: 'drop'
    displayName: 'Publish build artifacts'
